name = "kmfe-api"
compatibility_date = "2023-12-01"
account_id = "9fc3c9c90b0ebf9a5f68da6ed7deb3dc"

# [vars]
# MY_VARIABLE = "production_value"

[[kv_namespaces]]
binding = "kmfe"
id = "0176bec80c8d4cae92f522a3db727762"

[[kv_namespaces]]
binding = "debugs"
id = "020fb879ee484933a5359b875e9223d3"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""